[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

[colors.primary]
foreground = "#ECE1D7"
background = "#292522"

[colors.normal]
black      = "#34302C"
red        = "#BD8183"
green      = "#78997A"
yellow     = "#E49B5D"
blue       = "#7F91B2"
magenta    = "#B380B0"
cyan       = "#7B9695"
white      = "#C1A78E"

[colors.bright]
black      = "#867462"
red        = "#D47766"
green      = "#85B695"
yellow     = "#EBC06D"
blue       = "#A3A9CE"
magenta    = "#CF9BC2"
cyan       = "#89B3B6"
white      = "#ECE1D7"
